"""Frozen input contract for Unicorn V2 wide bdamage datasets."""

from __future__ import annotations


BDAMAGE_FILE_SUFFIX = ".bdamage.txt"
BDAMAGE_POSITION_COUNT = 5

BDAMAGE_FIT_COLUMNS = (
    "CTfreq",
    "GAfreq",
    "A",
    "q",
    "c",
    "phi",
    "Zfit",
    "fitCT0",
    "fitGA0",
    "nll",
)

BDAMAGE_POSITION_METRICS = (
    "K5",
    "N5",
    "K3",
    "N3",
    "Dx5",
    "Dx3",
)

BDAMAGE_POSITION_COLUMNS = tuple(
    f"{metric}_{position}"
    for position in range(BDAMAGE_POSITION_COUNT)
    for metric in BDAMAGE_POSITION_METRICS
)

BDAMAGE_SCHEMA_VERSION = "unicorn_bdamage_v2"
BDAMAGE_DIRECT_COUNT_SCOPE = "direct"
BDAMAGE_SUBTREE_COUNT_SCOPE = "subtree"
BDAMAGE_DAMAGE_SCOPE = "subtree"

BDAMAGE_EXTERNAL_ID_COLUMN = "#taxid"
BDAMAGE_INTERNAL_ID_COLUMN = "taxid"
BDAMAGE_DIRECT_COUNT_COLUMN = "direct_count"
BDAMAGE_SUBTREE_COUNT_COLUMN = "subtree_count"
BDAMAGE_MMM_POSITIONS_COLUMN = "mmm_positions"
BDAMAGE_DIRECT_MMM_COLUMN = "direct_mmm_base64"
BDAMAGE_MMM_VALUES_PER_POSITION = 32
BDAMAGE_MMM_BYTES_PER_POSITION = 128
# The producer stores this value in an unsigned byte.
BDAMAGE_MAX_MMM_POSITIONS = 255

BDAMAGE_IDENTITY_COLUMNS = (
    BDAMAGE_INTERNAL_ID_COLUMN,
    BDAMAGE_DIRECT_COUNT_COLUMN,
    BDAMAGE_SUBTREE_COUNT_COLUMN,
    "name",
)

BDAMAGE_BINARY_COLUMNS = (
    BDAMAGE_DIRECT_MMM_COLUMN,
)

BDAMAGE_INTEGER_COLUMNS = (
    BDAMAGE_INTERNAL_ID_COLUMN,
    BDAMAGE_DIRECT_COUNT_COLUMN,
    BDAMAGE_SUBTREE_COUNT_COLUMN,
    BDAMAGE_MMM_POSITIONS_COLUMN,
)

BDAMAGE_FLOAT_COLUMNS = (
    *BDAMAGE_FIT_COLUMNS,
    *BDAMAGE_POSITION_COLUMNS,
)

BDAMAGE_TEXT_COLUMNS = (
    "name",
    *BDAMAGE_BINARY_COLUMNS,
)

BDAMAGE_COLUMNS = (
    *BDAMAGE_IDENTITY_COLUMNS,
    *BDAMAGE_FIT_COLUMNS,
    *BDAMAGE_POSITION_COLUMNS,
    BDAMAGE_MMM_POSITIONS_COLUMN,
    *BDAMAGE_BINARY_COLUMNS,
)

BDAMAGE_HEADER_COLUMNS = (
    BDAMAGE_EXTERNAL_ID_COLUMN,
    *BDAMAGE_COLUMNS[1:],
)

BDAMAGE_COLUMN_COUNT = len(BDAMAGE_COLUMNS)
BDAMAGE_HEADER = "\t".join(BDAMAGE_HEADER_COLUMNS)
