"use strict";

(function initUnicornGraphEngineDom(globalObject) {
  const namespace = globalObject.UnicornGraphEngine = globalObject.UnicornGraphEngine || {};

  if (namespace.els) {
    return;
  }

  namespace.els = {
    app: document.getElementById("app"),
    sidebar: document.getElementById("sidebar"),
    controls: document.getElementById("controls"),
    sidebarToggle: document.getElementById("sidebarToggle"),
    toggleRemoteSection: document.getElementById("toggleRemoteSection"),
    remoteSectionBody: document.getElementById("remoteSectionBody"),
    toggleFilesSection: document.getElementById("toggleFilesSection"),
    filesSectionBody: document.getElementById("filesSectionBody"),
    toggleMetadataSection: document.getElementById("toggleMetadataSection"),
    metadataSectionBody: document.getElementById("metadataSectionBody"),
    toggleOptionsSection: document.getElementById("toggleOptionsSection"),
    optionsSectionBody: document.getElementById("optionsSectionBody"),
    toggleReportsSection: document.getElementById("toggleReportsSection"),
    reportsSectionBody: document.getElementById("reportsSectionBody"),
    toggleAgentSection: document.getElementById("toggleAgentSection"),
    agentSectionBody: document.getElementById("agentSectionBody"),
    agentMeta: document.getElementById("agentMeta"),
    agentProviderSelect: document.getElementById("agentProviderSelect"),
    agentModelSelect: document.getElementById("agentModelSelect"),
    agentApiKey: document.getElementById("agentApiKey"),
    agentBaseUrl: document.getElementById("agentBaseUrl"),
    agentProviderState: document.getElementById("agentProviderState"),
    toggleLogSection: document.getElementById("toggleLogSection"),
    logSectionBody: document.getElementById("logSectionBody"),
    agentPrompt: document.getElementById("agentPrompt"),
    agentSendBtn: document.getElementById("agentSendBtn"),
    agentClearBtn: document.getElementById("agentClearBtn"),
    agentTranscript: document.getElementById("agentTranscript"),
    uncollapseBtn: document.getElementById("uncollapseBtn"),
    uncollapseTipsBtn: document.getElementById("uncollapseTipsBtn"),
    subtreeReportBtn: document.getElementById("subtreeReportBtn"),
    rankReportBtn: document.getElementById("rankReportBtn"),
    selectDescendantsBtn: document.getElementById("selectDescendantsBtn"),
    selectToRankBtn: document.getElementById("selectToRankBtn"),
    selectToRankValue: document.getElementById("selectToRankValue"),
    clearSelectionBtn: document.getElementById("clearSelectionBtn"),
    lcaInputs: document.getElementById("lcaInputs"),
    lcaListFile: document.getElementById("lcaListFile"),
    addLcaBtn: document.getElementById("addLcaBtn"),
    clearLcaListBtn: document.getElementById("clearLcaListBtn"),
    remoteUser: document.getElementById("remoteUser"),
    remoteHost: document.getElementById("remoteHost"),
    connectBtn: document.getElementById("connectBtn"),
    uploadBtn: document.getElementById("uploadBtn"),
    copyTunnelBtn: document.getElementById("copyTunnelBtn"),
    connectionState: document.getElementById("connectionState"),
    tunnelCommand: document.getElementById("tunnelCommand"),
    tunnelHint: document.getElementById("tunnelHint"),
    remoteDatasetsPanel: document.getElementById("remoteDatasetsPanel"),
    remoteRefreshBtn: document.getElementById("remoteRefreshBtn"),
    remoteSelectAllBtn: document.getElementById("remoteSelectAllBtn"),
    remoteClearAllBtn: document.getElementById("remoteClearAllBtn"),
    remoteDatasetsMeta: document.getElementById("remoteDatasetsMeta"),
    remoteDatasetsList: document.getElementById("remoteDatasetsList"),
    nodesFile: document.getElementById("nodesFile"),
    namesFile: document.getElementById("namesFile"),
    metadataFile: document.getElementById("metadataFile"),
    metadataSummaryPanel: document.getElementById("metadataSummaryPanel"),
    metadataSummaryMeta: document.getElementById("metadataSummaryMeta"),
    metadataSummaryFields: document.getElementById("metadataSummaryFields"),
    metadataFieldSelect: document.getElementById("metadataFieldSelect"),
    metadataFieldColorMeta: document.getElementById("metadataFieldColorMeta"),
    metadataFieldColorList: document.getElementById("metadataFieldColorList"),
    metadataSelectedMeta: document.getElementById("metadataSelectedMeta"),
    metadataSelectedList: document.getElementById("metadataSelectedList"),
    renderBtn: document.getElementById("renderBtn"),
    centerBtn: document.getElementById("centerBtn"),
    countViewMode: document.getElementById("countViewMode"),
    toggleTableBtn: document.getElementById("toggleTableBtn"),
    countMode: document.getElementById("countMode"),
    scaleMode: document.getElementById("scaleMode"),
    minReads: document.getElementById("minReads"),
    minReadsValue: document.getElementById("minReadsValue"),
    minReadsScale: document.getElementById("minReadsScale"),
    minReadsMax: document.getElementById("minReadsMax"),
    searchBox: document.getElementById("searchBox"),
    controlsResize: document.getElementById("controlsResize"),
    summaryPanel: document.getElementById("summaryPanel"),
    summaryResize: document.getElementById("summaryResize"),
    status: document.getElementById("status"),
    chartWrap: document.getElementById("chartWrap"),
    svg: document.getElementById("treeSvg"),
    tooltip: document.getElementById("tooltip"),
    readCount: document.getElementById("readCount"),
    taxonCount: document.getElementById("taxonCount"),
    visibleCount: document.getElementById("visibleCount"),
    missingCount: document.getElementById("missingCount"),
    selectedCount: document.getElementById("selectedCount"),
    tablePanel: document.getElementById("tablePanel"),
    tablePanelTitle: document.getElementById("tablePanelTitle") || document.querySelector("#tablePanel h2"),
    tableResize: document.getElementById("tableResize"),
    pcoaMetric: document.getElementById("pcoaMetric"),
    pcoaBtn: document.getElementById("pcoaBtn"),
    barplotBtn: document.getElementById("barplotBtn"),
    exportMatrixBtn: document.getElementById("exportMatrixBtn"),
    subtreeReport: document.getElementById("subtreeReport"),
    sourceLegend: document.getElementById("sourceLegend"),
    topTableWrap: document.getElementById("topTableWrap"),
    topTable: document.getElementById("topTable"),
    clientLogMeta: document.getElementById("clientLogMeta"),
    clientLog: document.getElementById("clientLog"),
    clearClientLogBtn: document.getElementById("clearClientLogBtn"),
  };
})(window);
